-- Candidate Pipeline for RAT Apps
-- Run this in Supabase SQL Editor (Dashboard → SQL Editor → New query)

-- Create candidates table
CREATE TABLE IF NOT EXISTS public.candidates (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  email text,
  phone text,
  irata_level text,  -- '1', '2', '3', or null
  location text DEFAULT 'Gold Coast',
  source text DEFAULT 'Seek',  -- Seek, Indeed, Website, Referral, LinkedIn, Walk-in, Other
  status text NOT NULL DEFAULT 'new',  -- new, screened, shortlisted, phone_interview, in_person, hired, pool, rejected
  skills text[] DEFAULT '{}',  -- Array of skill tags
  notes text,
  cover_letter_keyword boolean DEFAULT false,  -- Did they include "Highly organized" in cover letter?
  screening_score integer,  -- 0-100 screening score
  added_by text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz
);

-- Add indexes for common queries
CREATE INDEX IF NOT EXISTS idx_candidates_status ON public.candidates(status);
CREATE INDEX IF NOT EXISTS idx_candidates_irata ON public.candidates(irata_level);
CREATE INDEX IF NOT EXISTS idx_candidates_location ON public.candidates(location);
CREATE INDEX IF NOT EXISTS idx_candidates_created ON public.candidates(created_at DESC);

-- Enable RLS (Row Level Security)
ALTER TABLE public.candidates ENABLE ROW LEVEL SECURITY;

-- Allow authenticated and anon access (matching existing app pattern with name+PIN auth)
CREATE POLICY "Allow all access to candidates" ON public.candidates
  FOR ALL
  USING (true)
  WITH CHECK (true);

-- Grant access
GRANT ALL ON public.candidates TO anon;
GRANT ALL ON public.candidates TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;

-- Add comment for documentation
COMMENT ON TABLE public.candidates IS 'Candidate pipeline for recruitment tracking. Statuses flow: new → screened → shortlisted → phone_interview → in_person → hired/pool/rejected';
COMMENT ON COLUMN public.candidates.cover_letter_keyword IS 'Whether candidate included the secret keyword "Highly organized" in their cover letter (filters out people who dont read the ad)';
COMMENT ON COLUMN public.candidates.status IS 'Pipeline status: new, screened, shortlisted, phone_interview, in_person, hired, pool, rejected';
COMMENT ON COLUMN public.candidates.skills IS 'Array of skill/cert tags e.g. {IRATA,EWP,confined_space,rigging}';
